// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5rKDuuMylanI_soe5aM5VUl2QfOSK4zo',
    appId: '1:273132779636:web:a6ca4b13fd20cb1fecb921',
    messagingSenderId: '273132779636',
    projectId: 'manga-app-8a3b4',
    authDomain: 'manga-app-8a3b4.firebaseapp.com',
    databaseURL: 'https://manga-app-8a3b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'manga-app-8a3b4.appspot.com',
    measurementId: 'G-BZYZS2FYCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE5WR_JBu6my_SWPTqPH08rZCzvbGl06g',
    appId: '1:273132779636:android:785865e0bbb56f32ecb921',
    messagingSenderId: '273132779636',
    projectId: 'manga-app-8a3b4',
    databaseURL: 'https://manga-app-8a3b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'manga-app-8a3b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo1o6-NMTz5IE_mt7V_mvNj58FRHNky0w',
    appId: '1:273132779636:ios:639887235446f45fecb921',
    messagingSenderId: '273132779636',
    projectId: 'manga-app-8a3b4',
    databaseURL: 'https://manga-app-8a3b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'manga-app-8a3b4.appspot.com',
    iosClientId: '273132779636-ipqrbm955b7hj1g1tl6giikv1kgcj4nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.comicApp',
  );
}
